//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.10 at 02:37:51 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengis.net/wms", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.geospeed.ogc.impl.wms.xml.v1_3_0;
